services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Madj2k\CopyrightGuardian\:
    resource: '../Classes/*'

  Madj2k\CopyrightGuardian\Command\CheckFileMetadataCommand:
    tags:
      - name: 'console.command'
        command: 'copyright_guardian:checkFileMetadata'
        schedulable: true
